### ISSUE TITLE
GUI Crashing for > 100 audio files

### ISSUE THREAD

**Issue by camillenoufi** [Voice-Lab/VoiceLab#7]
I am running the GUI version of the program on Mac OS 11.5.2, and when I try to start processing > ~100 audio files, the program consistently crashes.  I am able to load them into the editor, just not start the processing.  About a month ago I was not running into this problem.  I cannot feasibly manually upload and run the processing in batches, as I have ~20k 1 second files I am trying to process.

Any suggestions?  Thanks!

**Comment by drfeinberg** [comment]
I will look into this asap.

**Comment by drfeinberg** [comment]
Have you downloaded the latest version? 1.0.1? 1.0.0 has a bug that will crash if you use the default settings (bug was in jitter PCA)?

**Comment by camillenoufi** [comment]
Thanks for the quick reply! I did just re-download and try to run, but unfortunately I am having the same issues.

**Comment by drfeinberg** [comment]
Ok.. I'll see what I can figure out. Not sure what's going on there, but we'll get to the bottom of it for sure.

**Comment by camillenoufi** [comment]
Thanks! I'll keep an eye out and let you know if I can more specifically figure out what is causing the crashing on my end. Just to confirm, the [OS X link](https://github.com/Voice-Lab/VoiceLab/releases/download/v1.0.1/VoiceLab.zip) currently on the ReadME is for version 1.0.1 ?

**Comment by drfeinberg** [comment]
I think so, but here's the link just in case: https://github.com/Voice-Lab/VoiceLab/releases/download/v1.0.1/VoiceLab.zip

**Comment by camillenoufi** [comment]
running the Python build and looking at the output, it seems like the crash is coming from some calculation relating to Jitter and a minimum pitch value being a 'string' and "not being a number."  Potentially there is something in one of my audio files that causes this error that is only happening once I scale up in number of files?  Here's the terminal error message: 

`Traceback (most recent call last):
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/VoicelabWizard/InputTab.py", line 211, in onclick_start
    self.start_process()  # start the pipeline - code in VoiceLabTab.VoiceLabTab
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/VoicelabWizard/VoicelabTab.py", line 26, in start_process
    pipeline_results = self.data_controller.start_processing(
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/VoicelabWizard/VoicelabController.py", line 298, in start_processing
    pipeline_results = pipeline.start()
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 120, in start
    results = self.run_pass(True, results=results)
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 153, in run_pass
    self.run_pass(True, results, i_pass)
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 153, in run_pass
    self.run_pass(True, results, i_pass)
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 153, in run_pass
    self.run_pass(True, results, i_pass)
  [Previous line repeated 7 more times]
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 148, in run_pass
    _done = self.run_node(root, results, i_pass)
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 200, in run_node
    self.run_node(child, results, i_pass)
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/pipeline/Pipeline.py", line 181, in run_node
    results[i_pass][node] = node.process()
  File "/Users/camillenoufi/Applications/VoiceLab/Voicelab/toolkits/Voicelab/MeasureJitterNode.py", line 65, in process
    point_process: object = call(
parselmouth.PraatError: Argument "Minimum pitch" should be a number, not a string.`

**Comment by drfeinberg** [comment]
Thanks for your patience here.  I'm working on this now... The kids were sick last week and it's just me maintaining the software.

I suspect there may be something wrong with your sound file. 

If Argument "Minimum pitch" is a string, it means that Praat-Parselmouth could not find pitch values in the appropriate range and cannot process the file any further. This usually happens when the sound file is silence, doesn't have a periodic component in it, or that periodic component is not in the frequency range of human voice pitch.  I can't replicate the error on my end, but I've seen this sort of thing before, so that's my suspicion.

The code was previously wrapped in a try/except statement, which I forgot to add back in after the last edits.  What will happen in the next update is that it should now return "Jitter Measurement Failed" instead of crashing.  But please check you file out.  The program will continue, but it probably won't ever give you a valid measure.  I've wrapped the code back up into the try/except statement and will work on compiling the software for another update asap.  So if you need the code now, and you're comfortable, you could clone the repo again (or do a git pull) and run it out of python.  Otherwise, I'm working on getting this compiled this week.  I've updated the code on GitHub, so it should be ready for you.  Please let me know if it's working or if you run into any other trouble.

Best,
David

**Comment by drfeinberg** [comment]
I got windows and mac files up now too.

**Comment by camillenoufi** [comment]
Thanks for the help! Yes I too suspected as such.  I was working on short files where occasionally some of the files contained rough/hoarse voice with no periodic content.  I tested these individually and they caused the crash.  Thanks for the update - I'll try them out on the update soon and post here if anything arises.
